// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zigcpatkbgzorbkuravw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InppZ2NwYXRrYmd6b3Jia3VyYXZ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwODkwODgsImV4cCI6MjA2NjY2NTA4OH0.q5NQn-b-D5_JMxOTay-hb8Rq6unY23qJ1-HE5CYKjts";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);